spring:
  profiles:
   actvive: local
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry: http://localhost:8081

app:
  topic:
    receive: kstreaminput

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.codebigbear.kafka.consumer: DEBUG


server:
  port: 8080